/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists;

import org.eclipse.xtext.linking.ILinkingService;
import org.spf.cmakelists.linking.CMakeListsLinkingService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CMakeListsRuntimeModule extends AbstractCMakeListsRuntimeModule {
	
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return CMakeListsLinkingService.class;
	}
}
