/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists;

import org.eclipse.emf.ecore.EPackage;
import org.spf.CMakeLists.CMakeListsPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CMakeListsStandaloneSetup extends CMakeListsStandaloneSetupGenerated {

	public static void doSetup() {
		new CMakeListsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://spf.org/cmakelists")) {
			EPackage.Registry.INSTANCE.put("http://spf.org/cmakelists", CMakeListsPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
