/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.spf.cmakelists.CMakeListsRuntimeModule;
import org.spf.cmakelists.CMakeListsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CMakeListsIdeSetup extends CMakeListsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CMakeListsRuntimeModule(), new CMakeListsIdeModule()));
	}
	
}
