/*
 * generated by Xtext 2.21.0
 */
package org.spf.launchfile.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class LaunchFileIdeModule extends AbstractLaunchFileIdeModule {
}
