/*
 * generated by Xtext 2.21.0
 */
package org.spf.launchfile.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.spf.launchfile.dsl.LaunchFileRuntimeModule;
import org.spf.launchfile.dsl.LaunchFileStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LaunchFileIdeSetup extends LaunchFileStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LaunchFileRuntimeModule(), new LaunchFileIdeModule()));
	}
	
}
