/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.validation;

import org.eclipse.xtext.validation.Check;
import org.spf.CMakeLists.CMakeListsPackage;
import org.spf.CMakeLists.FindPackage;
import org.spf.CMakeLists.ProjectInstruction;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class CMakeListsValidator extends AbstractCMakeListsValidator {
	public final static String VALIDATION_PROJECT_NAME = "ValidationProjectName";
	public final static String VALIDATION_PACKAGE_REQUIRED = "ValidationPackageRequired";

	@Check
	public void checkProjectNameIsSnakeCase(ProjectInstruction pi) {
		for (char c : pi.getDeclaredPackageName().getName().toCharArray()) {
			if (Character.isUpperCase(c)) {
				warning("Package name should be snake case", CMakeListsPackage.eINSTANCE.getProjectInstruction_DeclaredPackageName(),
						VALIDATION_PROJECT_NAME, pi.getDeclaredPackageName().getName());
				break;
			}
		}
	}

	@Check
	public void checkFindPackageIsRequired(FindPackage fp) {
		if (!fp.getRequired()) {
			warning("All packages should be REQUIRED.", CMakeListsPackage.eINSTANCE.getFindPackage_Name(),
					VALIDATION_PACKAGE_REQUIRED, fp.getName());
		}
	}
	
}
