/*
 * generated by Xtext 2.21.0
 */
package org.spf.launchfile.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LaunchFileStandaloneSetup extends LaunchFileStandaloneSetupGenerated {

	public static void doSetup() {
		new LaunchFileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
