/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.spf.CMakeLists.FindPackage;
import org.spf.CMakeLists.ProjectInstruction;
import org.spf.cmakelists.validation.CMakeListsValidator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class CMakeListsQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(CMakeListsValidator.VALIDATION_PROJECT_NAME)
	public void snakeCaseName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Convert to snake case", "Convert to snake case.", "upcase.png",
				new ISemanticModification() {
					public void apply(EObject element, IModificationContext context) {
						((ProjectInstruction) element).getDeclaredPackageName().setName((CamelCase2SnakeCase(issue.getData()[0])));
					}
				});
	}

	@Fix(CMakeListsValidator.VALIDATION_PACKAGE_REQUIRED)
	public void addRequiredToFindPackage(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Add REQUIRED", "Add REQUIRED to find_package.", "upcase.png",
				new ISemanticModification() {
					public void apply(EObject element, IModificationContext context) {
						((FindPackage) element).setRequired(true);
					}
				});
	}

	private static String CamelCase2SnakeCase(String t) {
		StringBuilder ret = new StringBuilder();
		for (int i = 0; i < t.length(); ++i) {
			char c = t.charAt(i);
			if (Character.isUpperCase(c)) {
				if (i != 0) {
					ret.append("_");
				}
			}
			ret.append(Character.toLowerCase(c));
		}
		return ret.toString();
	}
}
