/*
 * generated by Xtext 2.21.0
 */
package org.spf.launchfile.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LaunchFileAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/spf/launchfile/dsl/parser/antlr/internal/InternalLaunchFile.tokens");
	}
}
