/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.spf.cmakelists.parser.antlr.internal.InternalCMakeListsParser;
import org.spf.cmakelists.services.CMakeListsGrammarAccess;

public class CMakeListsParser extends AbstractAntlrParser {

	@Inject
	private CMakeListsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCMakeListsParser createParser(XtextTokenStream stream) {
		return new InternalCMakeListsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CMakeListsFile";
	}

	public CMakeListsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CMakeListsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
