/*
 * generated by Xtext 2.22.0
 */
package org.spf.packagexml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PackageXMLUiModule extends AbstractPackageXMLUiModule {

	public PackageXMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
