/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.spf.cmakelists.services.CMakeListsGrammarAccess;

@SuppressWarnings("all")
public class CMakeListsSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CMakeListsGrammarAccess grammarAccess;
	protected AbstractElementAlias match_IfInstruction___IDTerminalRuleCall_3_3_or_MATCHESKeyword_3_2_or_ORKeyword_3_1_or_STRINGTerminalRuleCall_3_4__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CMakeListsGrammarAccess) access;
		match_IfInstruction___IDTerminalRuleCall_3_3_or_MATCHESKeyword_3_2_or_ORKeyword_3_1_or_STRINGTerminalRuleCall_3_4__a = new AlternativeAlias(true, true, new TokenAlias(false, false, grammarAccess.getIfInstructionAccess().getIDTerminalRuleCall_3_3()), new TokenAlias(false, false, grammarAccess.getIfInstructionAccess().getMATCHESKeyword_3_2()), new TokenAlias(false, false, grammarAccess.getIfInstructionAccess().getORKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getIfInstructionAccess().getSTRINGTerminalRuleCall_3_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * terminal STRING:
	 * 			'"' ( '\\' .  | !('\\'|'"') )* '"' |
	 * 			"'" ( '\\' .  | !('\\'|"'") )* "'"
	 * 		;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_IfInstruction___IDTerminalRuleCall_3_3_or_MATCHESKeyword_3_2_or_ORKeyword_3_1_or_STRINGTerminalRuleCall_3_4__a.equals(syntax))
				emit_IfInstruction___IDTerminalRuleCall_3_3_or_MATCHESKeyword_3_2_or_ORKeyword_3_1_or_STRINGTerminalRuleCall_3_4__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('OR' | 'MATCHES' | ID | STRING)*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'if' '(' (ambiguity) ')' 'endif' '(' ')' (rule start)
	 *     (rule start) 'if' '(' (ambiguity) ')' instructions+=Instruction
	 *     (rule start) 'if' '(' (ambiguity) predicate+='AND'
	 *     predicate+='AND' (ambiguity) ')' 'endif' '(' ')' (rule end)
	 *     predicate+='AND' (ambiguity) ')' instructions+=Instruction
	 *     predicate+='AND' (ambiguity) predicate+='AND'
	 */
	protected void emit_IfInstruction___IDTerminalRuleCall_3_3_or_MATCHESKeyword_3_2_or_ORKeyword_3_1_or_STRINGTerminalRuleCall_3_4__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
