/*
 * generated by Xtext 2.22.0
 */
package org.spf.launchfile.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLaunchFileScopeProvider extends DelegatingScopeProvider {
}
