/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCMakeListsScopeProvider extends DelegatingScopeProvider {
}
