/*
 * generated by Xtext 2.22.0
 */
package org.spf.packagexml;

import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.spf.PackageXML.PackageXMLPackage;
/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PackageXMLStandaloneSetup extends PackageXMLStandaloneSetupGenerated {

	public static void doSetup() {
		new PackageXMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	

	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://spf.org/packagexml")) {
			EPackage.Registry.INSTANCE.put("http://spf.org/packagexml", PackageXMLPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
