/*
 * generated by Xtext 2.22.0
 */
package org.spf.cmakelists.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CMakeListsUiModule extends AbstractCMakeListsUiModule {

	public CMakeListsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
